version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER =root
      - MYSQL_PASSWORD=BmwGsa1150
      - MYSQL_ROOT_PASSWORD=BmwGsa1150
    ports:
      - '3307:3306'
  # Wait for MySQL to be joinable.
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306 -timeout 360s'  
  
  library:
    container_name: library-api
    build:
      context: ./
    image: library-api
    depends_on:
      check-db-started:
        condition: service_completed_successfully
    ports:
      - 8888:8080
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: library
#    volumes:
#      - ./:/src
