#FETCHING THE OFFICIAL MAVEN IMAGE FROM DOCKER HUB TO USE IT IN DOCKER IMAGE
#SO I CAN HAVE A ENCAPSULATED OS WITH MAVEN AND JAVA
FROM maven:3.8.6-openjdk-8-slim as maven-build 


#COPY LOCAL FILES(FILES INSIDE DOCKERFILE DIRECTORY) TO APP DIRECTORY
ADD . /app 

#GO TO APP DIRECTORY
WORKDIR /app

#TELLING MAVEN TO RUN POM.XML ,WHICH EXISTS INSIDE APP FOLDER (THAT ABOVE STEP BROUGHT US)
RUN ["mvn","clean","install","-DskipTests"]

#
#UP UNTIL HERE WE HAVE BUILD THE WAR FILE
#-----------------------------------------------

#WE NOW NEED A TOMCAT SO WE CAN DEPLOY WAR
#FETCHING TOMCAT (WITH JAVA 8)FROM DOCKER HUB
FROM tomcat:9-jdk8

EXPOSE 8080

##COPYING WAR ARTIFACT BUILT IN LINE 16 TO THE TOMCAT WEBAPPS FOLDER
COPY --from=maven-build /app/target/library-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/library.war

CMD ["catalina.sh", "run"]